---
- name: remove gnome apps
  dnf:
    name: "{{ old_pkgs }}"
    state: absent

- name: update apps
  dnf:
    name: "*"
    state: latest

- name: install custom apps
  dnf:
    name:  "{{ new_pkgs }}"
    state: present
