- name: create 00_dflat_theme
  file:
    path: /etc/dconf/db/local.d/00_dflat_theme
    state: touch

- name: create entry
  include_tasks: nest0/theme-entry.yml
  loop: "{{ dconf_overrides.keys() | list }}"
  loop_control:
    loop_var: dconf_ns

- name: create 00_dflat_theme override
  file:
    path: /etc/dconf/db/local.d/locks/00_dflat_theme
    state: touch

- name: Set dconf locks
  lineinfile:
    dest: /etc/dconf/db/local.d/locks/00_dflat_theme
    line: "/{{ item | replace ('.', '/') }}"
  with_items: "{{ dconf_locks }}"

- name: dconf update
  shell: dconf update

